# Site settings
email: jacob1818@gmail.com
baseurl: "/db/"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Jacob's ... blog(?)
description: Short collection of insights and thoughts. Feel free to tag along, together we are strong.
url: "http://jacobsalzberg.github.io/db"
twitter_username: jacobjsalzberg
default_img: http://jademineresources.com/wp-content/uploads/2015/07/nephrite-jade-1.jpg

# Profile settings
name: Jacob's blog(?)
profile_img: "https://jacobsalzberg.github.io/db//static/profile_img.jpg"
profile: Hello my name is Jacob. I was born in Sao Paulo. Welcome to my world.
social:
  github: http://github.com/jacobsalzberg
  facebook: http://www.facebook.com/jacob.salzberg
  linkedin: http://www.linkedin.com/in/jacobsalzberg
  twitter: https://twitter.com/jacobjsalzberg


# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
